modLoader = "javafml"
loaderVersion = "[43,)"
license = "C0-1.0"
issueTrackerURL="https://github.com/vgrynch/block-disappear-fix/issues"

[[mods]]
modId = "block_disappear_fix"
version = "1.0.0-forge"
displayName = "block_disappear_fix"
logoFile = "icon.png"
authors = "vgrynch, Tropheus Jay, Patbox"
description = '''
Fixes a vanilla bug limiting total Blockstates to ~500k
'''

[[dependencies.block_disappear_fix]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.block_disappear_fix]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"
